const quotes = [
  "A vida é o que acontece enquanto você está ocupado fazendo outros planos. - John Lennon",
  "O sucesso é a capacidade de passar de um fracasso para outro sem perder o entusiasmo. - Winston Churchill",
  "A única coisa que fica entre você e seu objetivo é a história que você continua contando a si mesmo sobre por que não pode alcançá-lo. - Jordan Belfort",
  "A melhor vingança é um sucesso maciço. - Frank Sinatra",
  "A única maneira de fazer um excelente trabalho é amar o que você faz. - Steve Jobs",
  "A vida é o que acontece enquanto você está ocupado fazendo outros planos. - John Lennon",
  "Acredite em si mesmo e em tudo que você é capaz de realizar. - Mahatma Gandhi",
  "O sucesso não é final, o fracasso não é fatal: o que importa é a coragem de continuar. - Winston Churchill",
  "A única maneira de fazer um bom trabalho é amar o que você faz. - Steve Jobs",
  "Se você pode sonhar, você pode fazer. - Walt Disney",
  "A dor da disciplina pesa menos que o peso do arrependimento. - Jim Rohn",
  "Nunca desista dos seus sonhos. Se você pode sonhar, você pode realizá-los. - Walt Disney",
  "O que você faz hoje é mais importante do que o que você diz que vai fazer amanhã. - Abraham Lincoln",
  "A única jornada é a que se faz para dentro de si mesmo. - Rainer Maria Rilke",
  "O sucesso é a soma de pequenos esforços repetidos dia após dia. - Robert Collier",
  "Não tenha medo de errar. Tenha medo de não tentar. - Wayne Gretzky",
  "A vida é uma aventura ousada ou nada. - Helen Keller",
  "O único limite para o seu sucesso é a sua mente. - Brian Tracy",
  "Se você pode imaginar, você pode criar. - Albert Einstein",
  "O sucesso não é definitivo, o fracasso não é fatal: o que importa é a coragem de continuar. - Winston Churchill",
  "Não espere pelo momento perfeito. Comece agora e faça cada momento perfeito. - Mark Twain",
  "A única maneira de fazer um bom trabalho é amar o que você faz. - Steve Jobs",
  "Se você pode sonhar, você pode fazer. - Walt Disney",
  "A dor da disciplina pesa menos que o peso do arrependimento. - Jim Rohn",
  "Nunca desista dos seus sonhos. Se você pode sonhar, você pode realizá-los. - Walt Disney",
  "O que você faz hoje é mais importante do que o que você diz que vai fazer amanhã. - Abraham Lincoln",
  "A única jornada é a que se faz para dentro de si mesmo. - Rainer Maria Rilke",
  "O sucesso é a soma de pequenos esforços repetidos dia após dia. - Robert Collier",
  "Não tenha medo de errar. Tenha medo de não tentar. - Wayne Gretzky",
  "A vida é uma aventura ousada ou nada. - Helen Keller",
  "O único limite para o seu sucesso é a sua mente. - Brian Tracy",
  "Se você pode imaginar, você pode criar. - Albert Einstein",
  "O sucesso não é definitivo, o fracasso não é fatal: o que importa é a coragem de continuar. - Winston Churchill",
  "Não espere pelo momento perfeito. Comece agora e faça cada momento perfeito. - Mark Twain",
  "A única maneira de fazer um bom trabalho é amar o que você faz. - Steve Jobs",
  "Se você pode sonhar, você pode fazer. - Walt Disney",
  "A dor da disciplina pesa menos que o peso do arrependimento. - Jim Rohn",
  "Nunca desista dos seus sonhos. Se você pode sonhar, você pode realizá-los. - Walt Disney",
  "O que você faz hoje é mais importante do que o que você diz que vai fazer amanhã. - Abraham Lincoln",
  "A única jornada é a que se faz para dentro de si mesmo. - Rainer Maria Rilke",
  "O sucesso é a soma de pequenos esforços repetidos dia após dia. - Robert Collier",
  "Não tenha medo de errar. Tenha medo de não tentar. - Wayne Gretzky",
  "A vida é uma aventura ousada ou nada. - Helen Keller",
  "O único limite para o seu sucesso é a sua mente. - Brian Tracy",
  "Se você pode imaginar, você pode criar. - Albert Einstein",
  "O sucesso não é definitivo, o fracasso não é fatal: o que importa é a coragem de continuar. - Winston Churchill",
  "Não espere pelo momento perfeito. Comece agora e faça cada momento perfeito. - Mark Twain",
  "A única maneira de fazer um bom trabalho é amar o que você faz. - Steve Jobs",
  "Se você pode sonhar, você pode fazer. - Walt Disney",
];

function generateQuote() {
  const randomIndex = Math.floor(Math.random() * quotes.length);
  const quote = quotes[randomIndex];
  document.getElementById('quote').textContent = quote;
}
